### ISSUE TITLE
Problem: API access control allows tokens without Enduro attributes

### ISSUE THREAD

**Issue by jraddaoui** [artefactual-sdps/enduro#1066]
**Describe the bug**

A user without Enduro attributes in the access token given by the OIDC provider may be able to access all API endpoints with ABAC enabled in the configuration.

**To Reproduce**

* Enable auth and ABAC in the API.
* Make sure the OIDC provider gives an access token without Enduro attributes:
  * The configured claim must be included in the token (some providers don't return an empty claim).
  * Parsing the attributes from the claim may involve filtering and roles mapping based on configuration (which could help to create an empty attributes slice).
* Make a request to the API endpoint with that token.

**Expected behavior**

All API endpoints at the moment should return a `403 Forbidden` error code.

**Additional context**

The [parsing function](https://github.com/artefactual-sdps/enduro/blob/main/internal/api/auth/token_verifier.go#L76-L148) returns a `nil` slice instead of an empty one if there are no Enduro attributes after parsing, filtering and mapping roles. That `nil` attributes slice is considered as ABAC disabled in the [check attributes function](https://github.com/artefactual-sdps/enduro/blob/main/internal/api/auth/claims.go#L15-L44) used from the endpoints.

**Comment by sallain** [comment]
Closing for now, client will let us know if there are any issues.
