### ISSUE TITLE
Problem: offcanvas sidebar close button is misplaced and other links don't close it

### ISSUE THREAD

**Issue by jraddaoui** [artefactual-sdps/enduro#1079]
**Describe the bug**

On the offcanvas sidebar the close button appears close to the heading instead of in the top-right corner. Also, the width of the sidebar increases compared to the default sidebar, which makes the navigation links look different.

Additionally, click any of the navigation links changes the page in the background, but it would be great if that also closes the offcanvas sidebar.

**To Reproduce**

On a small window width, click the top-left icon to show the offcanvas sidebar. Check the look and behavior of the navigation links.

**Expected behavior**

* Close button appears in the top-right corner.
* Navigation links and icons look the same or similar to the default sidebar appearence.
* Clicking a navigation link redirects and closes the offcanvas sidebar.

**Screenshots**

![image](https://github.com/user-attachments/assets/199137e7-b70f-4b0e-9dd0-f0a48b31e97f)

**Comment by fiver-watson** [comment]
LGTM! Keyboard navigation also worked well.
