### ISSUE TITLE
Problem: we don't have a good pattern to implement filtering, ordering and pagination in persistence

### ISSUE THREAD

**Issue by Diogenesoftoronto** [artefactual-sdps/enduro#514]
sdps_preprocessing implements a generic "Filter" type that can perform filtering of Ent queriers based on user parameters, e.g. filtering, ordering, etc... being generic means that the same pattern can be applied across multiple entities effortlessly.

**Comment by djjuhasz** [comment]
Commit e2cc8b34dfb7aff4270a83fd0f5d47c289c94d29 adds a general query filter implementation to the persistence and entclient layers.
