### ISSUE TITLE
Writing commands using ffcli

### ISSUE THREAD

**Issue by Diogenesoftoronto** [artefactual-sdps/enduro#518]
## Is your feature request related to a problem? Please describe.
Compiling multiple binaries for different commands in Enduro can be cumbersome, particularly when it comes to integration testing. Managing and distributing these binaries separately adds complexity to the development workflow.

## Describe the solution you'd like
It would be beneficial to have the capability to include multiple commands within a single binary in Enduro. This feature would greatly improve the development experience and enhance the efficiency of integration testing. Packaging and delivering applications with multiple commands would be simplified, making distribution and deployment easier. This feature would save developers time and effort, contributing to a more streamlined development workflow. Considering the use case, we are exploring the adoption of `ffcli`, a command-line interface library that can serve as a front-end for managing commands, testing, and configuration within the application. Additionally, it would be advantageous to have a setup process in place.

## Describe alternatives you've considered
As an alternative to `ffcli`, we currently use `cobra` and `viper` in `SDPS-preprocessing`. However, `cobra` is more suitable for complex command-line applications and may not be the ideal solution for the Enduro project.

## Additional context
The `sdps-api-service` is deprecated, and `ffcli` is used there. However, in other non-deprecated services, `cobra` is used. Transitioning those services to `ffcli` would be challenging due to their larger size and feature completeness. Given the deprecation of `sdps-api-service` and the inconsistent tooling across projects, it may be more practical to adopt `cobra` instead of making changes to the preprocessing application. Standardizing the approach to packaging and delivering multiple commands within a single binary would simplify the deployment process and improve overall application maintainability.

**Comment by sevein** [comment]
See https://github.com/artefactual-sdps/enduro/issues/574 for more details.
