### ISSUE TITLE
Problem: AIP names are not named after the transfer name

### ISSUE THREAD

**Issue by scollazo** [artefactual-sdps/enduro#656]
**Is your feature request related to a problem? Please describe.**

All the AIPs created by enduro have the name "enduro-\<UUID\>.zip", and when uncompressed, they have a folder named enduro-\<UUID\>

**Describe the solution you'd like**

Add a configuration setting that allows for AIPs  to be created using the transfer name, without the ".zip" suffix, so the folder is named <transfer_name>-UUID, and the AIP <transfer_name>-UUID.zip

**Describe alternatives you've considered**

**Additional context**

**Comment by djjuhasz** [comment]
Related: https://github.com/artefactual-labs/a3m/issues/352
