### ISSUE TITLE
Problem: API server returns empty replies

### ISSUE THREAD

**Issue by scollazo** [artefactual-sdps/enduro#715]
**Describe the bug**

Enduro API is not working

**To Reproduce**

- Build enduro ( current HEAD is df53cc17de93986bf5709894874e2a8b2fe44d84 )
- Test the API. 

I got:
```
curl http://127.0.0.1:9000/storage/location -vvv 
*   Trying 127.0.0.1:9000...
* Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> GET /storage/location HTTP/1.1
> Host: 127.0.0.1:9000
> User-Agent: curl/7.76.1
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server

```

**Expected behavior**

The Enduro API works

**Screenshots**

**Additional context**

The API was working on commit f3ba8079f19afdf69f2661a3bc269870af540fe5 , but stops working in 75e6fbcf6171b17c5e2dbc291ef4f8af3be8bf45

**Comment by sevein** [comment]
I haven't been able to reproduce this. Even when forcing the API handler to panic or return various errors, the server always returns some kind of HTTP response including the "X-Enduro-Version" header.

**Comment by sevein** [comment]
I haven't been able to reproduce this. Even when forcing the API handler to panic or return various errors, the server always returns some kind of HTTP response including the "X-Enduro-Version" header.
