### ISSUE TITLE
Problem: all README.md development documentation links broken

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-sdps/enduro#758]
**Describe the bug**

Clicking any of the links in the README.md https://github.com/artefactual-sdps/enduro#development-documentation-resources section results in a 404 "File not found" error.

**To Reproduce**

1. Go to https://github.com/artefactual-sdps/enduro#development-documentation-resources
2. Click on any link in that section
3. A 404 "file not found" error is returned

**Expected behavior**

Clicking a documentation link should load the relevant documentation page.

**Comment by sevein** [comment]
I will fix later today, including the links to the new locations of the manuals:
- https://enduro.readthedocs.io/user-manual/
- https://enduro.readthedocs.io/dev-manual/
