### ISSUE TITLE
Problem: Upload activity error

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-sdps/enduro#759]
**Describe the bug**

The upload activity is failing with a cryptic error: "cannot perform operation".

**To Reproduce**

1. Start processing a new transfer by adding it to the Minio SIP bucket
2. The "upload-activity" fails with the error message "cannot perform operation".

**Expected behavior**

The AIP should successfully upload to the Minio "aips" bucket, and the workflow should complete successfully.

**Screenshots**

![image](https://github.com/artefactual-sdps/enduro/assets/626135/27dd62c7-d150-4fef-9ce1-40d1b4694fe9)

**Additional context**

- Tested on my local Tilt dev environment
- I can reliably reproduce this error on main (@ 01af95dd4f5763aa25d7617496df66423040d38a) and commit 07f2497068889ea77acfc53c0f0df86089d49dfc
- Upload works on commit 7f592447135afc9ee6a7d4b06885c64d1b2648e4 (the commit before 07f2497068889ea77acfc53c0f0df86089d49dfc)

Full Temporal output:

```
{
  "message": "activity error",
  "source": "GoSDK",
  "stackTrace": "",
  "encodedAttributes": null,
  "cause": {
    "message": "cannot perform operation",
    "source": "GoSDK",
    "stackTrace": "",
    "encodedAttributes": null,
    "cause": null,
    "applicationFailureInfo": {
      "type": "ServiceError",
      "nonRetryable": false,
      "details": null
    }
  },
  "activityFailureInfo": {
    "scheduledEventId": "33",
    "startedEventId": "34",
    "identity": "1@enduro-a3m-0@",
    "activityType": {
      "name": "upload-activity"
    },
    "activityId": "33",
    "retryState": "MaximumAttemptsReached"
  }
}
```

**Comment by sevein** [comment]
Fixed in https://github.com/artefactual-sdps/enduro/pull/765.
