### ISSUE TITLE
Problem: when using Archivematica, AIPs need to be downloaded from the Archivematica UI

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/enduro#782]
**Is your feature request related to a problem? Please describe.**

When Enduro is deployed with Archivematica, users must go to the Archivematica interface to download an AIP. Ideally, we would like users to stay within the Enduro UI for simplicity.

**Describe the solution you'd like**

Enable Enduro package "download" button so that the AIP can be downloaded from within the Enduro user interface.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by djjuhasz** [comment]
Fixed by #847
