### ISSUE TITLE
Problem: when using Archivematica, processing info is not displayed in Enduro

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/enduro#783]
**Is your feature request related to a problem? Please describe.**

When using Enduro with a3m, users can see some information about processing in the Enduro UI. However, when using Archivematica, this information is not available, meaning that users need to go to the Archivematica UI to see this information. We would like to keep users in the Enduro UI for simplicity.

**Describe the solution you'd like**

Add more details about the various processing steps and outcomes to the UI for each workflow run.

**Describe alternatives you've considered**

None.

**Additional context**

This is how the page looks when using a3m:

![image](https://github.com/artefactual-sdps/enduro/assets/4612276/15bd705b-aecb-425c-bf98-1a62165f6fdf)

Specifically, the tasks at the bottom of the page are what we would like to replicate when using Archivematica.

**Comment by scollazo** [comment]
Related issue: https://github.com/archivematica/Issues/issues/1641

**Comment by djjuhasz** [comment]
Fixed by #803 and #804.
