### ISSUE TITLE
Problem: when Archivematica is waiting for manual input, this does not generate an error in Enduro

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/enduro#786]
**Is your feature request related to a problem? Please describe.**

When Archivematica is being used with Enduro, it is intended to be used in a fully automated way. The processing configuration should not be set to wait for manual input at any point. Currently, when this occurs, no error is reported in Enduro.

**Describe the solution you'd like**

If the Archivematica workflow pauses to wait for manual input, this should be reported as an error in Enduro.

**Describe alternatives you've considered**

None

**Additional context**

This is an assertion we are making about an Enduro + Archivematica solution. I will add it in to the documentation.

**Comment by djjuhasz** [comment]
Implemented in PR #781.

**Comment by sallain** [comment]
@djjuhasz can this issue be closed?

**Comment by djjuhasz** [comment]
@sallain do you want to leave it open as a reminder to add a note to the documentation?

**Comment by sallain** [comment]
No, I'm happy to work off of closed issues!
