### ISSUE TITLE
Problem: some activities only return `error`

### ISSUE THREAD

**Issue by sevein** [artefactual-sdps/enduro#800]
**Describe the bug**

A number of activities in this project are not returning a struct. This can lead to backward-compatibility issues if we add one in the future.  If we use a struct, the activity remains compatible even if the fields change. This means we can add, remove, or change fields in our struct without breaking the function signature.

Some examples:

* CopyToPermanentLocationActivity,
* CleanUpActivity,
* DeleteOriginalActivity,
* DisposeOriginalActivity,
* MoveToPermanentStorageActivity,
* PollMoveToPermanentStorageActivity,
* RejectPackageActivity,
* UploadActivity, or
* [DeleteTransferActivity].

**Expected behavior**

Always return a struct even if empty. Refer to the code example in https://docs.temporal.io/dev-guide/go/foundations#activity-return-values:

```go
// YourActivityResultObject is the struct returned from your Activity.
// Use a struct so that you can return multiple values of different types.
// Additionally, your function signature remains compatible if the fields change.
type YourActivityResultObject struct {
    ResultFieldX string
    ResultFieldY int
}
```

**Additional context**

I believe this is a future-proofing effort that will become more important when we hit production and as upgrades are rolled out progressively the system will have both old and new versions of workers running concurrently.

Related: https://github.com/artefactual-sdps/enduro/pull/787#discussion_r1409683586.

[DeleteTransferActivity]: https://github.com/artefactual-sdps/enduro/blob/174f7f057ac5fc7384292d34e9820b4ac4962f0e/internal/am/delete_transfer.go#L27

**Comment by Diogenesoftoronto** [comment]
Should we consider doing this for local activities as well? Some local activities use a uint instead of a struct as well which seems non-standard. Also for reference, we tend to name result structs like: 
```go
type OurActivityResult struct {
    FieldX string
    FieldY int
}
```

**Comment by djjuhasz** [comment]
@Diogenesoftoronto it makes sense to me to do this for local activities as well.  I think our naming convention is fine, I don't think adding a "Object" suffix is necessary or adds any valuable information.

**Comment by sevein** [comment]
> @Diogenesoftoronto it makes sense to me to do this for local activities as well.

Agree. In practice, I don't think local activity inputs/outputs are encoded because they're local to the worker, but it sounds like it's a good idea for consistency purposes.
