### ISSUE TITLE
Problem: Archivematica SFTP upload provides no progress updates

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-sdps/enduro#815]
**Describe the bug**

When uploading a transfer to Archivematica for preservation processing, the SFTP upload process does not provide any progress updates on the upload until the upload is complete.  For large transfers this means the workflow could be waiting for minutes or hours without any indication of whether the upload is still progressing, or if it has failed or stalled.

**To Reproduce**

1. [Configure Enduro to use Archivematica for preservation processing](https://enduro.readthedocs.io/dev-manual/archivematica/)
2. Upload a large transfer to the Enduro MinIO "sips" bucket
3. After the "upload transfer" activity starts, the Temporal UI shows a Workflow "ActivityTaskScheduled" Event for "UploadTransferActivity" until the upload has completed (with a 2 hour timeout until the activity fails).

**Expected behavior**

Enduro should provide regular updates to the user that the upload is still running and making progress.

**Screenshot**

![image](https://github.com/artefactual-sdps/enduro/assets/626135/76fb3ea2-a641-45db-be7d-cebddd51b026)

**Additional context**

None.

**Comment by sallain** [comment]
@djjuhasz what's the status of this?

**Comment by djjuhasz** [comment]
@sallain oh it was fixed with commit 8228ec6.  Github must not have recognized the issue number in the commit message.
