### ISSUE TITLE
Problem: complex tooling and environment variables in development setup

### ISSUE THREAD

**Issue by Diogenesoftoronto** [artefactual-sdps/enduro#823]
**Is your feature request related to a problem? Please describe.**

It can take quite a long time to get different environments setup for each developer and all the tooling installed to fit their machine.
There is also the problem of version those tools when problems arise. 
**Describe the solution you'd like**

A shareable environment via devbox, just like how we containerise our applications, we should containerise or development.

**Describe alternatives you've considered**
Vagrant from hashicorp, devcontainers.

**Additional context**
...

**Comment by joel-simpson** [comment]
another way to frame this is "our dev environment is complex and hard to debug"? a devbox container doesn't solve that exactly but you get more consistency in how all of the different variables are set
