### ISSUE TITLE
Problem: lack of timestamps for task lifecycle in Archivematica microservices

### ISSUE THREAD

**Issue by scollazo** [artefactual-sdps/enduro#832]
**Is your feature request related to a problem? Please describe.**

We have the list of archivematica services in the enduro ui, but not their actual start/end times. 

**Describe the solution you'd like**

Take advantage of the new "detailed" parameter in Archivematica API as described [here](https://github.com/artefactual/archivematica/pull/1879)

**Describe alternatives you've considered**

None

**Additional context**

Getting duration times in the enduro interface helps getting the system "real" performance .

**Comment by scollazo** [comment]
More info in https://github.com/artefactual-sdps/enduro/issues/783

**Comment by sallain** [comment]
Timestamps now appear in the database:

![image](https://github.com/artefactual-sdps/enduro/assets/4612276/db892d6b-5301-4892-b4b8-e125bd353803)

However, they don't appear in the UI:

![image](https://github.com/artefactual-sdps/enduro/assets/4612276/46053ccb-8f13-47a3-8ada-3aaaeff7d548)

Start and end time columns should appear in the UI as well, to the left of Outcome. Note: there is a related issue, #933; it may be sensible to tackle them both at the same time.
