### ISSUE TITLE
Problem: formatting issues in Working with Archivematica docs

### ISSUE THREAD

**Issue by sevein** [artefactual-sdps/enduro#837]
**Describe the bug**

There are some formatting issues in [Working with Archivematica](Working with Archivematica
https://enduro.readthedocs.io/dev-manual/archivematica/) introduced by https://github.com/artefactual-sdps/enduro/pull/828 and https://github.com/artefactual-sdps/enduro/pull/830.

**To Reproduce**

1. Visit https://enduro.readthedocs.io/dev-manual/archivematica/.
2. Look at the formatting issues.
3. Experience visual discomfort.
4. Feel the urge to fix ASAP.

**Comment by Diogenesoftoronto** [comment]
I tried to change this Unfortunately it does not seem read the docs actually renders checkboxes which is a bit annoying

**Comment by sevein** [comment]
It looks like mkdocs doesn't support [tasks lists](https://www.markdownguide.org/extended-syntax/#task-lists): https://www.markdownguide.org/tools/mkdocs/. I think that you have a couple of options:

1. Use this [Tasklist extension](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tasklist), or
2. Use a nested list.

I'd rather go with the second option, for me these checkboxes are misleading because we're not really providing any interactivity.

**Comment by Diogenesoftoronto** [comment]
> It looks like mkdocs doesn't support [tasks lists](https://www.markdownguide.org/extended-syntax/#task-lists): [markdownguide.org/tools/mkdocs](https://www.markdownguide.org/tools/mkdocs/). I think that you have a couple of options:
> 
> 1. Use this [Tasklist extension](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tasklist), or
> 2. Use a nested list.
> 
> I'd rather go with the second option, for me these checkboxes are misleading because we're not really providing any interactivity.

I am going to remove the checklist, I think there is a way to add interactivity but it does not look great because it won't persist (there are workarounds i think we could make that use local storage but after talking to @joel-simpson I do not think it is worth it.)
