### ISSUE TITLE
Problem: inconsistent bucket configuration across components

### ISSUE THREAD

**Issue by sevein** [artefactual-sdps/enduro#858]
**Describe the bug**

Enduro bootstraps instances of `*blob.Bucket` in several places, e.g. `watcher`, `upload` or `location`. `*blob.Bucket` is an abstraction provided by gocloud.dev that we've adopted to interact with blobstore.

These are some issues observed with the current approach:
* Lack of a shared configuration struct embeddable in different contexts (appconfig, databases, etc),
* Lack of support for URL-based buckets (useful during testing, e.g. `mem://` or simpler config),
* Use of AWS SDKv1 ([end of support announced](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/)), should use v2 instead!

**Additional context**

I'm planning to suggest the introduction of a new `bucket` package providing a shared configuration struct and a simple function to open a `*blob.Bucket` given such configuration. Future iterations could focus on deeper integration with the new facilities, e.g. `watcher.MinioConfig` to make use of the new config struct to define the bucket configuration.

**Comment by jraddaoui** [comment]
I think you solved this issue @sevein but, could this package be moved to the gotools repository? I think it will be useful for other projects.

**Comment by sevein** [comment]
> Could this package be moved to the gotools repository? I think it will be useful for other projects.

Done! https://pkg.go.dev/go.artefactual.dev/tools@v0.9.0/bucket
