### ISSUE TITLE
Problem: AIP creation shows too many jobs in the Enduro UI that shouldn't be visible

### ISSUE THREAD

**Issue by fiver-watson** [artefactual-sdps/enduro#950]
**Describe the bug**

When running an AIP creation workflow, Archivematica currently displays 124 tasks. Many of these are for decisions the user is not prompted to make (e.g. "Run File format identification?") based on the configuration, or as steps that a user does not need to see (e.g. "Moving to processing directory"). This clutters the interface and makes it harder for operators to easily glean useful workflow information.  

**To Reproduce**

1. Start an ingest
2. Wait for it to complete processing
3. Examine the result on the package details page of the related SIP

**Expected behavior**

Operators should only see key tasks shown in the Enduro UI when running preservation workflows, that impart useful information on what tasks are currently being performed.

**Additional context**

This issue is the first in what will hopefully be a multi-part development effort, to eventually add a more curated and customized list of tasks in a preservation / AIP creation workflow, with useful outcome information (and/or error information) shown for each. New issues will be filed for future increments. 

Analysis work on this topic is being done in this spreadsheet: 

* https://docs.google.com/spreadsheets/d/10jByMHs6kTl4B22VCnwlEd2tLPb5tdJ595wZg-J96ts/edit#gid=1083719011

For now / for this issue, any row marked in red in the "AM-Enduro list (2024)" sheet should be prevented from displaying in the Enduro user interface.

**Comment by sallain** [comment]
Note: even though this isn't really specific to error messages, it's a precursor to error message work that we will do in future sprints.

**Comment by fiver-watson** [comment]
Hi @jraddaoui !

Overall, I think this is looking good. 

Of the 3 activities you identified that we didn't have included originally  in the spreadsheet - i.e.:

* Scan for viruses in directories (row 17)
* Scan for viruses in submission documentation (row 94)
* Scan for viruses in metadata (row 106)

I think that if these activities ARE configured in AM to run, then it makes sense to show them in the Enduro UI. It's comforting to know that all of these things are being scanned, lol! So, unless Sara disagrees when she reviews this, I would say no changes needed here. 

A couple quick questions for you - in reviewing the spreadsheet against a `little_borndigital_SIP_20111020_BFB_v60.zip` sample in Enduro, I did find 2 rows in the spreadsheet that were not present in the UI: 

* Validate preservation derivatives (row 75)
* Check for manual normalized files (row 81)

It makes sense to me that the validate activity is not showing, since I believe that we are not currently configured to do any normalization (i.e. we create no preservation derivatives) for the SFA workflow, so that task wouldn't show. 

I am curious about the other one - namely: 

Do you know why "Identify manual normalized files" (row 58 in the spreadsheet) DOES run, but "Check for manual normaliized files doesn't? And... more of an AM question, but why does identifying these files happen BEFORE the check for them?

Those were the only discrepancies I found, and I suspect they are configuration issues (and AM weirdness) rather than implementation problems on this ticket, but thought I would check first. Otherwise, looks great!

**Comment by fiver-watson** [comment]
Radda discussed some of my questions earlier. Overall I think this  feature looks good and can go out in the next SFA release for their feedback, but we agreed to leave this ticket open for @sallain's input

**Comment by jraddaoui** [comment]
These are the AM jobs we keep:

https://github.com/artefactual-sdps/enduro/blob/main/internal/am/job_tracker.go#L16-L59

We filter the jobs we get from AM creating preservation tasks only for the jobs in that list. The jobs we get depends on the processing configuration used in AM, I was using the default `automated` processing config, so there may be a few discrepancies on what I was able to see.

We should probably consider as much processing options and jobs as we can, so let me know if something is missing and what changes should I do in the processing configuration to see those jobs.

**Comment by sallain** [comment]
Looking beautiful
