### ISSUE TITLE
Problem: PREMIS files are not validated

### ISSUE THREAD

**Issue by sallain** [artefactual-sdps/enduro#951]
**Is your feature request related to a problem? Please describe.**

Whether generated by Enduro (through a child workflow) or included in a SIP, PREMIS XML files should be validated before the package is sent to preservation. Archivematica/a3m can parse a PREMIS file to add the file's events to the AIP METS, which happens quite late in the AM/a3m workflow - ensuring that the PREMIS file is valid will hopefully avoid errors at this late point.

**Describe the solution you'd like**

Add a new activity to validate the premis.xml file against the [PREMIS v3 schema](https://www.loc.gov/standards/premis/v3/premis.xsd) before sending to AM/a3m, ensuring that it's well-formed and valid.

PREMIS files generated by Enduro child workflows should always be validated. A PREMIS file included in a transfer may have been validated in advance, so it might not be necessary to validate these. A reasonable approach might be to validate any PREMIS file in the SIP's `metadata` directory, regardless of origin, as this is the file that will be picked up by Archivematica/a3m.

**Describe alternatives you've considered**

None

**Additional context**

* There is a related task to generate a PREMIS file based on child workflow tasks - [preprocessing-sfa#19](https://github.com/artefactual-sdps/preprocessing-sfa/issues/19)
* Information about this activity should be visible in the Enduro UI, as described in #949 
* I've added a hand-tooled, valid, multi-object sample PREMIS file in the comments

**Comment by sallain** [comment]
[premis-annotated-multi.zip](https://github.com/user-attachments/files/15516826/premis-annotated-multi.zip)

**Comment by sallain** [comment]
Note: I've only listed validating against the schema as a first iteration. Other checks might include:

* Ensuring that each object listed in the PREMIS file exists in the transfer
* Ensuring that identifiers (for objects, events, and agents) are unique, and replacing them with unique IDs if needed
* Ensuring that there are no extra agents
* and possibly others!

**Comment by fiver-watson** [comment]
Note additionally that this is something that will be used repeatedly for any Enduro user performing custom ingest activities that might generate PREMIS, and/or anyone submitting their own PREMIS files with a SIP.  For this reason, ideally this will be implemented as a reusable temporal activity, rather than a client-specific child workflow.

**Comment by fiver-watson** [comment]
@mcantelon also, as discussed in the meeting today: 

Let's make this a general "Validate XML" task for its first pass, that can accept both a file to validate and a schema file to use for the validation as inputs.

**Comment by mcantelon** [comment]
PR for CR: https://github.com/artefactual-sdps/temporal-activities/pull/21

**Comment by jraddaoui** [comment]
There are some comments about this issue in https://github.com/artefactual-sdps/preprocessing-sfa/issues/22#issuecomment-2223129249.

**Comment by sallain** [comment]
PREMIS file looks good and it's being properly parsed into the METS. I think we can finally put this issue to bed!
