### ISSUE TITLE
Problem: Only 20 most recent packages are available in Enduro UI; no way to see older results

### ISSUE THREAD

**Issue by fiver-watson** [artefactual-sdps/enduro#959]
**Describe the bug**

At present, only the 20 most recent packages that have been processed in Enduro are available in the Enduro packages tab. Any older packages cannot be seen. 

**To Reproduce**

1. Log into Enduro
2. Run 21 or more packages through
3. Try to access information about package 1

This is currently visible in this [dev](https://sfa-dev.archivematica.net:8844/packages) instance - by the ID #s in the package table, you can see that 80+ SIPs have been used. However, the page says "Showing 20/20", and the results are cut off after package 61 (counting backwards from package 80)

**Expected behavior**

A method of seeing older results in packages table should be added. For example: a pager. 

Would be nice eventually to have a setting that can adjust results per page, but that could also potentially be revisited in future deliverables.

**Comment by sallain** [comment]
![Image](https://github.com/artefactual-sdps/enduro/assets/4612276/2e7e0c8f-c9b4-47d7-8067-35b415452bf8)

**Comment by sallain** [comment]
As an initial implementation, this definitely works! @djuhasz I know you have a list of follow-ups you'd like to do; do you want to open a new ticket(s) or do you prefer to continue working off this one?

**Comment by djjuhasz** [comment]
@sara I'll open new tickets for future pager improvements.
