### ISSUE TITLE
Problem: Metadata summary button is displayed despite having no associated function currently

### ISSUE THREAD

**Issue by fiver-watson** [artefactual-sdps/enduro#985]
**Describe the bug**

The Package details page includes a "Metadata summary" button. However this button does not currently work, and is set as inactive. Despite this, many users in Talk-Aloud testing found themselves clicking it and expecting some sort of corresponding action. 

We should hide this button until we are ready to add actual functionality to it. 

**To Reproduce**

1. Login
2. Click on Packages
3. Select a package, and click on its name to go to the Package details page
4. See the "Metadata summary" button in the Summary area
5. Click it

Nothing happens. 

**Expected behavior**

The button does something useful to end users... Or else, it is not displayed. 

**Additional context**

I think that [METSFlask](https://github.com/tw4l/METSFlask?tab=readme-ov-file) provides an excellent starting point for the kind of information and possible display that such a feature COULD use in the future. 

For now however, let's just remove the distraction.

**Comment by mcantelon** [comment]
PR: https://github.com/artefactual-sdps/enduro/pull/1008

**Comment by mcantelon** [comment]
Fix merged!
