### ISSUE TITLE
Problem: Packages count only ever counts packages listed on current page

### ISSUE THREAD

**Issue by fiver-watson** [artefactual-sdps/enduro#988]
## Description

The Packages browse page in Enduro includes a count of page results and total packages, just below the page header. However, this counter constantly only ever reads `20/20` - it is currently only ever listing the total package count as the current total page count. 

**To Reproduce**

1. Log into enduro
2. Make sure you have more than 20 packages processed
3. Navigate to the Packages page
4. Look at the count below the Packages header

**Error encountered**

Package count reads: 

> Showing 20/20

## Expected outcome

This counter should: 

* List the number of results on the current page as the first value, and
* List the TOTAL number of ingested packages as the second value

**Comment by djjuhasz** [comment]
Fixing the total package count is going to require changes to the Enduro API - the current `/package` GET endpoint doesn't return a count of the total number of packages stored in Enduro.  This change will require changes to the Goa API layer, the package service layer, and the persistence layer so this is not a good first issue to tackle.

**Comment by sallain** [comment]
Thanks for the context, @djjuhasz!

**Comment by fiver-watson** [comment]
👍 LGTM! Also, I personally did end up liking have the results count both at the top and the bottom of the page. Even on a relatively large monitor, , the 20 results regularly went beyond my screen, so having that count repeated at the bottom by the pager (esp given that the pager doesn't reload the page fully and bring you back to the top) works well.
