### ISSUE TITLE
Problem: There is no way to filter package results by workflow status

### ISSUE THREAD

**Issue by fiver-watson** [artefactual-sdps/enduro#989]
## Description

One of the feedback elements from the recent Talk-Aloud usability tests. Currently users have no way of filtering package results by status. This can make it hard to find specific package when there are many results. 

**To Reproduce**

1.Log in
2. Navigate to Packages
3. try to see only Done packages, or only those with Errors

**Resulting error**

No method available to filter results by workflow status

**Expected behavior**

Users can easily filter results by workflow status to better discover relevant packages.

## Proposed solution

Following this feedback, we drafted 2 mockups to cover potential implementation solutions - one using tabs, and the other using a drop-down menu. After reviewing it with the team, no team members had strong preferences one way or the other. We then decided to get input from another Enduro user in a different context - Maaike, who operates the MoMA Enduro instance as part of their managed service. 

Here is Maaike's feedback: 

> In my personal opinion, I prefer the Tabs option - I would find this a more efficient way to monitor the progress of a batch and view errors. The current status filter in [MoMA's version of] Enduro is similar to the drop-down filter option, which while functional, is slightly more tedious to manage than a series of tabs that I could quickly flip between.

Consequently we propose that the first implementation try using the **tabs**. A mockup is included below: 

![enduro-pkg-status-filter-tabs](https://github.com/artefactual-sdps/enduro/assets/5068277/b0b2ae0c-fc1c-41cf-8326-502c4db63ed8)

**Comment by sallain** [comment]
Note: https://github.com/artefactual-sdps/enduro/pull/1036 allows for filtering by package status in the API; however, package filtering still needs to be implemented in the UI

**Comment by fiver-watson** [comment]
hi hi! Functionally, the tabs work great! However, I have a little bit of feedback on the design:

* At minimum, it seems like there might have been an icon mixup? i would suggest swapping the icons for Error and In Progress

![Image](https://github.com/user-attachments/assets/023df679-abf2-4233-98fd-a34853f952d2)


* Is it possible for me to browse the icon set you are using, and see what other options are available? I'd like to see if there are any alternative candidates. For example, though i can see that each is set to 24x24 size, it looks strange to me that the "Done" and "In progress" circle icons don't appear to be the same size. Also, if we can find something appropriate, it could be good to pick something for the All tab...

**Comment by jraddaoui** [comment]
@fiver-watson https://icon-sets.iconify.design/clarity/

**Comment by fiver-watson** [comment]
Thanks @jraddaoui !

@djjuhasz some thoughts: 

* For "All", perhaps we can try [blocks-group-line](https://icon-sets.iconify.design/clarity/blocks-group-line/)
* For "In progress" I would suggest we try [sync-line](https://icon-sets.iconify.design/clarity/sync-line/)
* For "error", [remove-line](https://icon-sets.iconify.design/clarity/remove-line/)
* For "Queued" I thought perhaps [clock-line](https://icon-sets.iconify.design/clarity/clock-line/) or [hourglass-line](https://icon-sets.iconify.design/clarity/hourglass-line/)
* For "Done" I think you previously used check-circle-line, but they should look the same size if instead you use [success-standard-line](https://icon-sets.iconify.design/clarity/success-standard-line/)

There are additional alternative options for each, but these seemed like the best picks to me. Open to other suggestions though!

**Comment by djjuhasz** [comment]
Updated icons:
![image](https://github.com/user-attachments/assets/abb07930-2874-47a0-9700-e9078491d51f)

**Comment by fiver-watson** [comment]
Nice! Thanks for doing that, @djjuhasz !
