### ISSUE TITLE
Regression: status updates are no longer showing up in real time for packages

### ISSUE THREAD

**Issue by fiver-watson** [artefactual-sdps/enduro#991]
## Description and steps to reproduce

Enduro makes use of web sockets to update the status of tasks and preservation action workflows  shown in the user interface in real time as they progress. Recently, in our development and QA environments, this has ceased working: now users need to manually refresh the browser to see updates on package and task statuses. 

**To Reproduce**

1. Ensure you have a test sample of sufficient size, so it will take at least a few minutes to process. 
2. Use MinIO to begin a SIP ingest
3. Quickly open Enduro, and navigate to your package details page once the package appears in the browse page, ideally while the package status is still in progress
4. Wait

**Resulting error**

The status will not update from In Progress to Done (or Error), and new tasks will not appear in the Preservation actions, unless you manually refresh the browser, or else navigate elsewhere and return.

**Expected behavior**

New tasks should appear in the Preservation actions area in real time as they are carried out, and the status of the package itself should be updated accordingly without the user needing to manually refresh or leave and return.

## Additional context

@jraddaoui has reminded the team that we also need to review the websocket usage against the recent implementation of our policy-based access control, so that permissions for web socket updates are properly assigned in line with the configured permissions of a given user etc.

**Comment by sallain** [comment]
LGTM!
