### ISSUE TITLE
Problem: Dev environment MinIO web UI log in often fails

### ISSUE THREAD

**Issue by djjuhasz** [artefactual-sdps/enduro#998]
**Describe the bug**

When I try to log in to the MinIO web console in the Tilt/k3d dev environment (at http://localhost:7460) I often get an "Unable to connect" error response after 30 - 60s.  When the error occurs the Tilt logs for the MinIO Resource display a port-forwarding error:

```
Reconnecting... Error port-forwarding minio (7460 -> 9001): creating stream: Timeout occurred
```

After the error occurs, reloading the MinIO web page usually works and displays the expected buckets.  The MinIO UI works fine from that point forward, unless I don't interact with it for a while (30+ minutes) at which point I see the log in challenge again, and my log in attempt again results in the "Unable to connect" error.

**To Reproduce**

1. Start the Enduro dev environment with `tilt up`
2. Open the MinIO web UI (http://localhost:7460) in a web browser
3. Click the login button (SSO)
4. Enter your login credentials
5. Wait for the error response

**Expected behavior**

I should be able to log in without an error.

**Screenshots**

![Screenshot from 2024-07-24 14-30-19](https://github.com/user-attachments/assets/b031d191-e993-43c0-be77-4c0413807a6b)

![Screenshot from 2024-07-24 14-34-07](https://github.com/user-attachments/assets/10a5349b-02fb-4dba-ae6c-b43b6b311334)

![Screenshot from 2024-07-24 14-34-33](https://github.com/user-attachments/assets/752ec559-f06d-4123-899f-24c7578f54e0)

![Screenshot from 2024-07-24 14-34-51](https://github.com/user-attachments/assets/7021fb0a-d340-4d3f-9a0a-05e608fecb77)

**Additional context**

None

**Comment by jraddaoui** [comment]
Thanks @djjuhasz, in the meantime while we look at this properly, the "Other Authentication Methods" should allow you to log in with the previous minio/minio123 user/pass, maybe that method gives you a bigger window.

**Comment by djjuhasz** [comment]
It looks like this is a known problem with the MinIO web console: 
- Minio bug report: https://github.com/minio/console/issues/2539
- Upstream k8s report: https://github.com/kubernetes/kubectl/issues/1368
